version: '3.7'
services:
  web:
    build: .
    container_name: medserve_server
    restart: unless-stopped
    ports:
      - '8443:8443'
    volumes:
      - '~/data/docker_data/WebServer:/WebServer'
    network_mode: 'bridge'
