version: '3.7'
services:
  web:
    build: .
    container_name: medserve_server
    restart: unless-stopped
    ports:
      - '8443:8443'
    volumes:
      - 'app:/app'
    network_mode: 'host'
volumes:
  app:
